# Site settings
title: Rigatoni Blog
email: your_email@example.com
author: Team Rigatoni
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl: ""
url: "http://rigatoni.github.io"
google_analytics:
animated: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
